title: Shailendra Singh
description: Long Form Jekyll theme built with SASS

# url: https://long-haul.netlify.app
baseurl: "/website"
url: "https://shailendrasingh.github.io"
paginate_path: "blog/page:num/"
permalink: "pretty"
remote_theme: "brianmaierjr/long-haul"

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: brianmaierjr
    twitter: brianmaierjr
    facebook: brianmaierjr
    email: brimaidesigns@gmail.com
    linkedin: brianmaierjr

google_analytics: ""

disqus:
    shortname: brianmaierjr
